language: python
python:
    - "2.7"

# - "3.4"

# command to install dependencies
before_install:
	  - sudo apt-get update -qq
	  - sudo apt-get install -qq libpcap-dev
    - sudo apt-get install -qq python-pcapy
    - python -c "import pcapy" # Test the package is avaliable
install:
    - apt-get
    - pip install -r build-requirements.txt
    - pip install coveralls

script:
    coverage run --source=avstreamer setup.py test

after_success:
    coveralls
