language: python
python:
    - "2.7"

# - "3.4"

# command to install dependencies
install:
    - pip install -r build-requirements.txt --use-mirrors
    - pip install coveralls --use-mirrors

script:
    coverage run --source=moscowdjango,meetup manage.py test

after_success:
    coveralls
