language: python
python:
    - "2.7"

# - "3.4"

# command to install dependencies
install:
    - pip install -r build-requirements.txt
    - pip install coveralls

script:
    coverage run --source=avstreamer setup.py test

after_success:
    coveralls
